package BL;

/**
 * This class implements exceptions/errors generated by business-specific operations.
 *
 * @author Renaud
 */
public class BusinessException extends Exception{
    /**
     * No args constructor
     */
    public BusinessException(){
        super();
    }

    /**
     * Constructor with expanation message
     */
    public BusinessException(String message){
        super(message);
    }
}
