package DAL;
// Generated 18-Mar-2010 4:02:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game  implements java.io.Serializable {


     private Integer gameId;
     private Recurrentgame recurrentgame;
     private User user;
     private Location location;
     private Integer gameStatus;
     private int gameState;
     private Date dateHeure;
     private Integer maxPlayers;
     private String skillLevel;
     private Float fieldCost;
     private String comments;

    public Game() {
    }

	
    public Game(int gameState) {
        this.gameState = gameState;
    }
    public Game(Integer gameId, Recurrentgame recurrentgame, User user, Location location, Integer gameStatus, int gameState, Date dateHeure, Integer maxPlayers, String skillLevel, Float fieldCost, String comments) {
       this.gameId = gameId;
       this.recurrentgame = recurrentgame;
       this.user = user;
       this.location = location;
       this.gameStatus = gameStatus;
       this.gameState = gameState;
       this.dateHeure = dateHeure;
       this.maxPlayers = maxPlayers;
       this.skillLevel = skillLevel;
       this.fieldCost = fieldCost;
       this.comments = comments;
    }
   
    public Integer getGameId() {
        return this.gameId;
    }
    
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }
    public Recurrentgame getRecurrentgame() {
        return this.recurrentgame;
    }
    
    public void setRecurrentgame(Recurrentgame recurrentgame) {
        this.recurrentgame = recurrentgame;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Integer getGameStatus() {
        return this.gameStatus;
    }
    
    public void setGameStatus(Integer gameStatus) {
        this.gameStatus = gameStatus;
    }
    public int getGameState() {
        return this.gameState;
    }
    
    public void setGameState(int gameState) {
        this.gameState = gameState;
    }
    public Date getDateHeure() {
        return this.dateHeure;
    }
    
    public void setDateHeure(Date dateHeure) {
        this.dateHeure = dateHeure;
    }
    public Integer getMaxPlayers() {
        return this.maxPlayers;
    }
    
    public void setMaxPlayers(Integer maxPlayers) {
        this.maxPlayers = maxPlayers;
    }
    public String getSkillLevel() {
        return this.skillLevel;
    }
    
    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }
    public Float getFieldCost() {
        return this.fieldCost;
    }
    
    public void setFieldCost(Float fieldCost) {
        this.fieldCost = fieldCost;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


