package DAL;
// Generated 18-Mar-2010 4:02:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer locationId;
     private String fieldName;
     private String fieldDescription;
     private String fieldAddress;
     private byte[] fieldPhoto;
     private Set games = new HashSet(0);

    public Location() {
    }

	
    public Location(String fieldName, String fieldDescription, String fieldAddress) {
        this.fieldName = fieldName;
        this.fieldDescription = fieldDescription;
        this.fieldAddress = fieldAddress;
    }
    public Location(String fieldName, String fieldDescription, String fieldAddress, byte[] fieldPhoto, Set games) {
       this.fieldName = fieldName;
       this.fieldDescription = fieldDescription;
       this.fieldAddress = fieldAddress;
       this.fieldPhoto = fieldPhoto;
       this.games = games;
    }
   
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    public String getFieldDescription() {
        return this.fieldDescription;
    }
    
    public void setFieldDescription(String fieldDescription) {
        this.fieldDescription = fieldDescription;
    }
    public String getFieldAddress() {
        return this.fieldAddress;
    }
    
    public void setFieldAddress(String fieldAddress) {
        this.fieldAddress = fieldAddress;
    }
    public byte[] getFieldPhoto() {
        return this.fieldPhoto;
    }
    
    public void setFieldPhoto(byte[] fieldPhoto) {
        this.fieldPhoto = fieldPhoto;
    }
    public Set getGames() {
        return this.games;
    }
    
    public void setGames(Set games) {
        this.games = games;
    }




}


