package DAL;
// Generated 18-Mar-2010 4:02:28 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recurrentgame generated by hbm2java
 */
public class Recurrentgame  implements java.io.Serializable {


     private int recurrentGameId;
     private Integer frequency;
     private Date lastDatePlayed;
     private Set games = new HashSet(0);

    public Recurrentgame() {
    }

	
    public Recurrentgame(int recurrentGameId) {
        this.recurrentGameId = recurrentGameId;
    }
    public Recurrentgame(int recurrentGameId, Integer frequency, Date lastDatePlayed, Set games) {
       this.recurrentGameId = recurrentGameId;
       this.frequency = frequency;
       this.lastDatePlayed = lastDatePlayed;
       this.games = games;
    }
   
    public int getRecurrentGameId() {
        return this.recurrentGameId;
    }
    
    public void setRecurrentGameId(int recurrentGameId) {
        this.recurrentGameId = recurrentGameId;
    }
    public Integer getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }
    public Date getLastDatePlayed() {
        return this.lastDatePlayed;
    }
    
    public void setLastDatePlayed(Date lastDatePlayed) {
        this.lastDatePlayed = lastDatePlayed;
    }
    public Set getGames() {
        return this.games;
    }
    
    public void setGames(Set games) {
        this.games = games;
    }




}


