package DAL;
// Generated 18-Mar-2010 4:02:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private Userprofile userprofile;
     private String email;
     private String password;
     private Set games = new HashSet(0);

    public User() {
    }

	
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }
    public User(String username, Userprofile userprofile, String email, String password, Set games) {
       this.username = username;
       this.userprofile = userprofile;
       this.email = email;
       this.password = password;
       this.games = games;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Userprofile getUserprofile() {
        return this.userprofile;
    }
    
    public void setUserprofile(Userprofile userprofile) {
        this.userprofile = userprofile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getGames() {
        return this.games;
    }
    
    public void setGames(Set games) {
        this.games = games;
    }




}


